# gaunam visus users
GET http://localhost:8001/users 

###
# gaunam visus users
GET http://localhost:8001/users?archived=false
###

# gaunam visus users istrinti
GET http://localhost:8001/users?archived=true

###

# sukuriam nauja user
POST http://localhost:8001/users
Content-Type: application/json

{
  "name": "Serbentautas",
  "age": 18,
  "town": "Neveronys"
}

###

DELETE http://localhost:8001/users/5

###

#  edit vienai reiksmei
PATCH http://localhost:8001/users/5
Content-Type: application/json

{
  "archived": true
}

###

#  edit visoms reiksmems
PUT http://localhost:8001/users/6
Content-Type: application/json

{
  "name": "Serbentautas Bordiuras",
  "town": "Serbija",
  "age": 35
}